//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportProcess.DBContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUSPLAN_DOCUMENTS
    {
        public int DOCUMENT_ID { get; set; }
        public Nullable<int> NODE_ID { get; set; }
        public string DOCUMENT_LABEL { get; set; }
        public string PHYSICAL_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string STATUS { get; set; }
        public string CHECKOUT_USER_ID { get; set; }
        public Nullable<System.DateTime> CHECKOUT_DATE { get; set; }
        public string DOC_CASCADES_YN { get; set; }
        public string DOC_NOTES { get; set; }
        public Nullable<int> TOC_ID { get; set; }
        public string TYPE { get; set; }
    
        public virtual SUSPLAN_NODES SUSPLAN_NODES { get; set; }
    }
}
