//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportProcess.DBContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUSPLAN_TOC_HEADER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUSPLAN_TOC_HEADER()
        {
            this.SUSPLAN_SEC_HDR = new HashSet<SUSPLAN_SEC_HDR>();
            this.SUSPLAN_REPORT_Q = new HashSet<SUSPLAN_REPORT_Q>();
        }
    
        public int TOC_ID { get; set; }
        public Nullable<int> NODE_ID { get; set; }
        public string REPORT_NAME { get; set; }
        public string TOC_TYPE { get; set; }
        public Nullable<int> FIRST_SECTION_ID { get; set; }
        public string TOC_CASCADES_YN { get; set; }
        public Nullable<int> TOC_PAGE { get; set; }
        public string FOOTER_TEXT_LEFT { get; set; }
        public string FOOTER_TEXT_CENTER { get; set; }
        public string FOOTER_TEXT_RIGHT { get; set; }
        public string STD_PAGE_NUMBERS { get; set; }
        public string TOC_LAYOUT { get; set; }
        public string TOC_LEFT_MARGIN { get; set; }
        public string TOC_RIGHT_MARGIN { get; set; }
        public string TOC_FONT { get; set; }
        public string TOC_FONT_SIZE { get; set; }
        public string HEADER_FONT { get; set; }
        public string HEADER_FONT_SIZE { get; set; }
        public string HEADER_TEXT { get; set; }
        public string FOOTER_FONT { get; set; }
        public string FOOTER_FONT_SIZE { get; set; }
        public Nullable<int> FOOTER_START_ON_DOC { get; set; }
        public Nullable<int> HEADER_START_ON_DOC { get; set; }
        public string FOOTER_MARGIN_B { get; set; }
        public string FOOTER_MARGIN_R { get; set; }
        public string FOOTER_MARGIN_L { get; set; }
        public string COVER_PAGE { get; set; }
        public Nullable<int> COVER_PAGE_ID { get; set; }
        public string COVER_PAGE_YN { get; set; }
        public string TOC_YN { get; set; }
        public string FOOTER_OPT_C { get; set; }
        public string FOOTER_OPT_R { get; set; }
        public string FOOTER_OPT_L { get; set; }
        public string FOOTER_YN { get; set; }
        public Nullable<int> SVY { get; set; }
    
        public virtual SUSPLAN_NODES SUSPLAN_NODES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUSPLAN_SEC_HDR> SUSPLAN_SEC_HDR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUSPLAN_REPORT_Q> SUSPLAN_REPORT_Q { get; set; }
    }
}
