//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportProcess.DBContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUSPLAN_NODES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUSPLAN_NODES()
        {
            this.SUSPLAN_DOCUMENTS = new HashSet<SUSPLAN_DOCUMENTS>();
            this.SUSPLAN_TOC_HEADER = new HashSet<SUSPLAN_TOC_HEADER>();
        }
    
        public int NODE_ID { get; set; }
        public Nullable<int> PREVIOUS_NODE_ID { get; set; }
        public Nullable<int> NEXT_NODE_ID { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public Nullable<int> FIRST_CHILD_ID { get; set; }
        public Nullable<int> LEVEL_NUMBER { get; set; }
        public string DESCRIPTION { get; set; }
        public string L1_CAPTION { get; set; }
        public string L2_CAPTION { get; set; }
        public string L3_CAPTION { get; set; }
        public string L4_CAPTION { get; set; }
        public string L5_CAPTION { get; set; }
        public string L6_CAPTION { get; set; }
        public string L7_CAPTION { get; set; }
        public string L8_CAPTION { get; set; }
        public string L9_CAPTION { get; set; }
        public string L10_CAPTION { get; set; }
        public string DOCDIRECTORY_ID { get; set; }
        public string group_id { get; set; }
        public string ABS_PATH { get; set; }
        public string Include { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUSPLAN_DOCUMENTS> SUSPLAN_DOCUMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SUSPLAN_TOC_HEADER> SUSPLAN_TOC_HEADER { get; set; }
    }
}
