//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportProcess.DBContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUSPLAN_PARMS
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string ADLIB_VERSION { get; set; }
        public string DOC_STD_LOCATION_YN { get; set; }
        public string DOC_DIRECTORY { get; set; }
        public string DOC_DIRECTORY_B { get; set; }
        public string DOC_DIRECTORY_C { get; set; }
        public string DOC_DIRECTORY_D { get; set; }
        public string PAGE_TITLE { get; set; }
        public string ASST_ENABLED_YN { get; set; }
        public string SVC_RSTRT_ENABLED_YN { get; set; }
        public string ADLIB_SVC_NAME { get; set; }
        public string CRYMON_SVC_NAME { get; set; }
        public string RPTMON_SVC_NAME { get; set; }
        public string COLOR_MAIN_LIGHT { get; set; }
        public string COLOR_MAIN_MEDIUM { get; set; }
        public string COLOR_MAIN_DARK { get; set; }
        public string COLOR_ALT_LIGHT { get; set; }
        public string COLOR_ALT_MEDIUM { get; set; }
        public string COLOR_ALT_DARK { get; set; }
        public Nullable<int> PWD_MIN_LENGTH { get; set; }
        public Nullable<int> PWD_MAX_LENGTH { get; set; }
        public Nullable<int> PWD_EXP_DAYS { get; set; }
        public string PWD_MUST_INCL_NUMBER_YN { get; set; }
        public string PWD_MUST_INCL_LETTER_YN { get; set; }
        public string PWD_MUST_INCL_UC_YN { get; set; }
        public string PWD_MUST_INCL_LC_YN { get; set; }
        public string PWD_MUST_INCL_SPECIAL_YN { get; set; }
        public Nullable<int> PWD_HISTORY { get; set; }
        public Nullable<int> PWD_TRIES { get; set; }
        public string CRYMON_OUTPUT_TYPE { get; set; }
        public Nullable<int> CRYMON_SLEEP_SECS { get; set; }
        public Nullable<int> RPTMON_SLEEP_SECS { get; set; }
        public Nullable<int> RPTMON_LONG_SLEEP_SECS { get; set; }
        public string EXTRACT_STATUS { get; set; }
        public Nullable<System.DateTime> EXTRACT_START { get; set; }
        public Nullable<System.DateTime> EXTRACT_END { get; set; }
        public string SMTP_SERVER { get; set; }
        public string HEADING_SUFFIX { get; set; }
        public string MS_CODE_UPDATE_YN { get; set; }
        public string SP_DATABASE_VERSION { get; set; }
        public Nullable<int> AUTOSAVE_MINUTES { get; set; }
        public Nullable<int> SESSION_TIMEOUT_MINUTES { get; set; }
        public string LDAP_AUTHENTICATION_YN { get; set; }
        public string LDAP_HOST { get; set; }
        public string LDAP_BIND_USERID { get; set; }
        public string LDAP_BIND_PASSWORD { get; set; }
        public string LDAP_HOST_TYPE { get; set; }
        public string LDAP_CONTEXT { get; set; }
        public string LDAP_OBJECTCLASS { get; set; }
        public string EXTERNAL_AUTHENTICATION_YN { get; set; }
        public string EXT_AUTH_COOKIE_NAME { get; set; }
        public string EXT_AUTH_DELETE_COOKIE_YN { get; set; }
        public string SMTP_SERVER_USERID { get; set; }
        public string SMTP_SERVER_PASSWORD { get; set; }
        public string SMTP_SERVER_SSL_YN { get; set; }
        public string NOTIFICATION_PROVIDER { get; set; }
        public string NOTIFICATION_USER_LOC { get; set; }
        public string NOTIFICATION_SERVER_URL { get; set; }
        public string NOTIF_USERS_REFRESH { get; set; }
        public Nullable<System.DateTime> NOTIF_USERS_LAST_REFRESH { get; set; }
        public string SURVEY_RENAME { get; set; }
        public string SURVEY_RENAME_PLURAL { get; set; }
        public string NOTIFICATION_SHOW_USERS { get; set; }
        public string GEN_REPORT_TIMESTAMP_YN { get; set; }
        public string EMAIL_FORGOTTEN_PASSWORD_YN { get; set; }
        public string FORGOTTEN_PASSWORD_MSG { get; set; }
        public string GEN_REPORT_NATIVEAPPS_YN { get; set; }
        public string SMTP_RETURNEMAIL { get; set; }
        public string SP_GROUPS_YN { get; set; }
        public string NAVARRE_YN { get; set; }
        public string NAVARRE_DB { get; set; }
        public string NAVARRE_SERVER { get; set; }
        public string NAVARRE_USER { get; set; }
        public string NAVARRE_PASS { get; set; }
        public string IDASH_IP { get; set; }
        public string IDASH_INSTANCE_NAME { get; set; }
        public Nullable<int> IDASH_PORT { get; set; }
        public string notification_api_url { get; set; }
        public string SPMnuServerID { get; set; }
        public string SPMnuUserID { get; set; }
        public string SPMnuPassword { get; set; }
        public string SPMnuDBName { get; set; }
        public string EmailPending { get; set; }
        public string EmailApprove { get; set; }
        public string LDAP_email { get; set; }
        public string MIR3_REFRESH { get; set; }
        public string INCIDENTTNAME { get; set; }
        public string INCIDENTBNAME { get; set; }
        public string HOME_TAB { get; set; }
        public string BIND_CONTEXT { get; set; }
        public string USER_INIT_NAME { get; set; }
        public string USER_INIT_PASS { get; set; }
        public string USER_INIT_PASS_KEY { get; set; }
        public string USER_INIT_PASS_IV { get; set; }
        public Nullable<int> USER_INIT_CUST_ID { get; set; }
        public Nullable<int> USER_INIT_TEMP_ID { get; set; }
        public string USER_INIT_URL { get; set; }
        public Nullable<int> LDAP_RETRY { get; set; }
        public string SIGNON_IMG { get; set; }
        public string SAML_ISSUER_CERT { get; set; }
        public string SAML_SLO_URL { get; set; }
        public string SAML_URL { get; set; }
        public string SAML_YN { get; set; }
        public string DOC_TAB { get; set; }
        public string DELETE_DOC_YN { get; set; }
        public string DISABLED_USER_MSG { get; set; }
        public string EXPIRATION_DATE { get; set; }
        public string RESET_PASSWORD_MSG { get; set; }
        public string SP_APP_VERSION { get; set; }
        public Nullable<int> TOKEN_EXPIRATION { get; set; }
        public string USER_PROFILE_EDIT_YN { get; set; }
        public Nullable<int> MAX_TOTAL_USERS { get; set; }
        public Nullable<int> MAX_CONCURRENT_USERS { get; set; }
        public string USER_NAME_EDIT_YN { get; set; }
        public string USER_EMAIL_EDIT_YN { get; set; }
        public string USER_PHONE_EDIT_YN { get; set; }
        public string USER_TITLE_EDIT_YN { get; set; }
        public string USER_LOCATION_EDIT_YN { get; set; }
        public string USER_DEPARTMENT_EDIT_YN { get; set; }
        public string SMTP_USER_DISABLED_TPL { get; set; }
        public string SMTP_TOKEN_TPL { get; set; }
        public string SMTP_SERVER_PORT { get; set; }
        public Nullable<int> IDASH_TIMEOUT { get; set; }
    }
}
