//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportProcess.DBContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUSPLAN_SEC_HDR
    {
        public int SECTION_ID { get; set; }
        public Nullable<int> TOC_ID { get; set; }
        public string SECTION_NAME { get; set; }
        public Nullable<int> NEXT_SECTION_ID { get; set; }
        public Nullable<int> PREVIOUS_SECTION_ID { get; set; }
        public Nullable<int> PARENT_SECTION_ID { get; set; }
        public Nullable<int> CHILD_SECTION_ID { get; set; }
        public Nullable<int> FIRST_TOCDOC_ID { get; set; }
    
        public virtual SUSPLAN_TOC_HEADER SUSPLAN_TOC_HEADER { get; set; }
    }
}
