//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportProcess.DBContexts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UNIT_TESTContext : DbContext
    {
        public UNIT_TESTContext()
            : base("name=UNIT_TESTContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SUSPLAN_DOCUMENTS> SUSPLAN_DOCUMENTS { get; set; }
        public virtual DbSet<SUSPLAN_NODES> SUSPLAN_NODES { get; set; }
        public virtual DbSet<SUSPLAN_PARMS> SUSPLAN_PARMS { get; set; }
        public virtual DbSet<SUSPLAN_SEC_HDR> SUSPLAN_SEC_HDR { get; set; }
        public virtual DbSet<SUSPLAN_TOC_DOCUMENT> SUSPLAN_TOC_DOCUMENT { get; set; }
        public virtual DbSet<SUSPLAN_TOC_HEADER> SUSPLAN_TOC_HEADER { get; set; }
        public virtual DbSet<SUSPLAN_REPORT_Q> SUSPLAN_REPORT_Q { get; set; }
    }
}
